networks:
    app-network:
        driver: bridge
services:
  db_pg:
    image: postgres:15
    container_name: memoryCode-postgres
    networks:
      - app-network
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 5433:5432
  discovery-service:
    image: alexscorp/alexrep:s3
    container_name: memoryCode-discovery-service
    networks:
      - app-network
    env_file:
      - .env
    ports:
      - 8761:8761
  user-service:
    image: alexscorp/alexrep:s4
    container_name: memoryCode-user-service
    networks:
      - app-network
    depends_on:
      - discovery-service
      - db_pg
    env_file:
      - .env
    ports:
      - 8109:8109
  yandexgpt-service:
    container_name: memoryCode-yandexgpt-service
    image: alexscorp/alexrep:s2
    networks:
      - app-network
    depends_on:
      - discovery-service
    env_file:
      - .env
    ports:
      - 8101:8101
  memories-service:
    image: alexscorp/alexrep:s5
    container_name: memoryCode-memories-service
    networks:
      - app-network
    env_file:
      - .env
    depends_on:
      - discovery-service
    ports:
      - 8000:8000
    restart: always
    command: sh -c "python main.py"