networks:
    app-network:
        driver: bridge
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: memoryCode-RabbitMQ
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - app-network
