spring:
  application:
   name: user-service
  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    driver-class-name: org.postgresql.Driver
  config:
    import: optional:file:.env[.properties]
  cloud:
    openfeign:
      httpclient:
        follow-redirects: true
eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_HOST_CLIENT}:${DISCOVERY_PORT}/eureka
    fetch-registry: false
    register-with-eureka: false
server:
  port: 8109
logging:
  file:
    path: /logs
    name: user-service.log
