spring:
  config:
    import: optional:file:.env[.properties]
  application:
   name: memories-service
  rabbitmq:
    virtual-host: ${RABBITMQ_DEFAULT_VHOST}
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka
    fetch-registry: false
    register-with-eureka: false
