spring:
  config:
    import: optional:file:../.env
  application:
   name: memories-service
  rabbitmq:
    virtual-host: ${RABBITMQ_VHOST}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka
    fetch-registry: false
    register-with-eureka: false
