spring:
  application:
   name: yandexgpt-service
  config:
    import: optional:file:.env[.properties]
eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_HOST_CLIENT}:${DISCOVERY_PORT}/eureka
    fetch-registry: false
    register-with-eureka: false
server:
  port: 8104
yandex:
  gpt:
    api:
      indignity-key: b1g5og37bgh1ghh2s2qc
      key: AQVN1J4sCxYR98rj-tVppyp6gXQthbdmYvmgtO7a