spring:
  application:
   name: yandexgpt-service
  config:
    import: optional:file:.env[.properties]
eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_HOST_CLIENT}:${DISCOVERY_PORT}/eureka
    fetch-registry: false
    register-with-eureka: true
server:
  port: 8101
yandex:
  gpt:
    api:
      indignity-key:
      key:
springdoc:
  swagger-ui:
    path: /swagger-doc/swagger-ui.html
  api-docs:
    path:  /swagger-doc/api-docs
