spring:
  application:
   name: yandexgpt-service
  rabbitmq:
    virtual-host: ${RABBITMQ_DEFAULT_VHOST}
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
    stream:
      virtual-host: ${RABBITMQ_DEFAULT_VHOST}
    host: ${RABBITMQ_HOST}
  config:
    import: optional:file:.env[.properties]
eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_HOST}:${DISCOVERY_PORT}/eureka
    fetch-registry: false
    register-with-eureka: true
server:
  port: 8101
